#!/bin/bash
# One source of truth — edit the 5 hex values below, then run ./colors.sh

BACKGROUND="1C1A14"
TEXT="68694F"
ACCENT="737458"
INACTIVE="2C2A24"
URGENT="f53c3c"

DIR="$(cd "$(dirname "$0")" && pwd)"

BG_R=$((16#${BACKGROUND:0:2}))
BG_G=$((16#${BACKGROUND:2:2}))
BG_B=$((16#${BACKGROUND:4:2}))

TEXT_R=$((16#${TEXT:0:2}))
TEXT_G=$((16#${TEXT:2:2}))
TEXT_B=$((16#${TEXT:4:2}))

INACTIVE_R=$((16#${INACTIVE:0:2}))
INACTIVE_G=$((16#${INACTIVE:2:2}))
INACTIVE_B=$((16#${INACTIVE:4:2}))

BR_INACTIVE="$INACTIVE_R, $INACTIVE_G, $INACTIVE_B"

cat > "$DIR/colors.css" << EOF
@define-color background rgba($BG_R, $BG_G, $BG_B, 1.0);
@define-color text #$TEXT;
@define-color accent #$ACCENT;
@define-color inactive #$INACTIVE;
@define-color urgent #$URGENT;
EOF

cat > "$DIR/colors.rasi" << EOF
* {
    bg:                          #$BACKGROUND;
    foreground-color:            #$TEXT;
    foreground-color-alt:        #$ACCENT;
    accent-color:                #$ACCENT;
    border-color:                #$ACCENT;
    on:                          #$ACCENT;
    off:                         #$INACTIVE;
    urgent:                      #$URGENT;
}
EOF

cat > "$DIR/hyprland-colors.conf" << EOF
# Auto-generated from colors.sh
\$background = rgba(${BACKGROUND}ee)
\$text = rgb($TEXT)
\$accent = rgb($ACCENT)
\$inactive = rgb($INACTIVE)
\$urgent = rgb($URGENT)
EOF

mkdir -p ~/.config/swayosd
cat > ~/.config/swayosd/style.css << CSSEOF
window#osd {
  border-radius: 10px;
  border: 2px solid #$ACCENT;
  background: rgba($BG_R, $BG_G, $BG_B, 0.87);
}

window#osd #container {
  margin: 16px;
}

window#osd image,
window#osd label {
  color: rgba($TEXT_R, $TEXT_G, $TEXT_B, 1);
}

window#osd progressbar:disabled,
window#osd image:disabled {
  opacity: 0.5;
}

window#osd progressbar,
window#osd segmentedprogress {
  min-height: 6px;
  border-radius: 999px;
  background: transparent;
  border: none;
}

window#osd trough,
window#osd segment {
  min-height: 6px;
  border-radius: 999px;
  border: none;
  background: rgba($TEXT_R, $TEXT_G, $TEXT_B, 0.5);
}

window#osd progress,
window#osd segment.active {
  min-height: 6px;
  border-radius: 999px;
  border: none;
  background: rgba($TEXT_R, $TEXT_G, $TEXT_B, 1);
}

window#osd segment {
  margin-left: 8px;
}

window#osd segment:first-child {
  margin-left: 0;
}
CSSEOF

mkdir -p ~/.config/swaync
cat > ~/.config/swaync/style.css << CSSEOF
/* swaync style — generated by colors.sh */

* {
  font-family: "Inter", "Noto Sans", sans-serif;
}

.notification-row {
  outline: none;
  margin: 8px 10px;
}

.notification-row:focus,
.notification-row:hover {
  background: rgba($BG_R, $BG_G, $BG_B, 0.15);
  border-radius: 10px;
}

.notification {
  border-radius: 10px;
  border: 2px solid #$ACCENT;
  background: rgba($BG_R, $BG_G, $BG_B, 0.87);
  padding: 0;
  margin: 0;
}

.notification-content {
  background: transparent;
  padding: 12px;
}

.notification-default-action,
.notification-action {
  padding: 8px 12px;
  border-radius: 8px;
  background: rgba($BR_INACTIVE, 0.6);
  color: #$TEXT;
  border: 1px solid transparent;
}

.notification-default-action:hover,
.notification-action:hover {
  background: #$INACTIVE;
  border: 1px solid #$ACCENT;
}

.notification-action:not(:last-child) {
  border-radius: 8px;
}

.notification-action:disabled {
  opacity: 0.5;
}

.close-button {
  background: #$URGENT;
  color: #$BACKGROUND;
  border-radius: 50%;
  padding: 2px;
}

.image {
  border-radius: 8px;
}

.summary {
  font-size: 14px;
  font-weight: bold;
  color: #$TEXT;
}

.body {
  font-size: 12px;
  color: rgba($TEXT_R, $TEXT_G, $TEXT_B, 0.9);
}

.time {
  color: rgba($TEXT_R, $TEXT_G, $TEXT_B, 0.6);
}

.notification.critical {
  border: 2px solid #$URGENT;
}

.notification.critical .notification-default-action {
  border-top: 3px solid #$URGENT;
}

.control-center {
  border-radius: 10px;
  border: 2px solid #$ACCENT;
  background: rgba($BG_R, $BG_G, $BG_B, 0.92);
  padding: 8px;
}

.control-center-list {
  background: transparent;
}

.control-center-list-placeholder {
  color: #$TEXT;
  opacity: 0.6;
}

.control-center-clear-all {
  color: #$TEXT;
  background: rgba($BR_INACTIVE, 0.6);
}

.control-center-clear-all:hover {
  background: #$INACTIVE;
  color: #$ACCENT;
}

.floating-bar {
  background: rgba($BG_R, $BG_G, $BG_B, 0.9);
  color: #$TEXT;
  border-radius: 10px;
  border: 1px solid #$INACTIVE;
}
CSSEOF

cat > ~/.config/swaync/config.json << JSONEOF
{
  "\$schema": "/etc/xdg/swaync/configSchema.json",
  "ignore-gtk-theme": true,
  "positionX": "right",
  "positionY": "top",
  "layer": "overlay",
  "layer-shell": true,
  "layer-shell-cover-screen": true,
  "cssPriority": "user",
  "notification-2fa-action": true,
  "notification-inline-replies": false,
  "notification-body-image-height": 100,
  "notification-body-image-width": 200,
  "timeout": 10,
  "timeout-low": 5,
  "timeout-critical": 0,
  "fit-to-screen": true,
  "relative-timestamps": true,
  "notification-window-width": 360,
  "keyboard-shortcuts": true,
  "notification-grouping": true,
  "image-visibility": "when-available",
  "transition-time": 200,
  "hide-on-clear": true,
  "hide-on-action": true,
  "text-empty": "No Notifications",
  "script-fail-notify": true,
  "widgets": []
}
JSONEOF

echo "Wrote colors.css, colors.rasi, hyprland-colors.conf, swayosd/style.css, swaync/style.css, swaync/config.json"
