// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "afb06ba8-62f4-4bc3-99ef-2f94dc44e94c");
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1782148898);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1782148898);
user_pref("app.update.lastUpdateTime.suggest-ingest", 1782148896);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "0ef7f570-9f8d-4c17-b2ea-01f5a6472aaf");
user_pref("browser.contextual-services.contextId.timestamp-in-seconds", 1782148896);
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.ipProtection.added", true);
user_pref("browser.ipProtection.enabled", true);
user_pref("browser.ipProtection.stateCache", "unauthenticated");
user_pref("browser.ipProtection.usageCache", "");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1782148895);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 169);
user_pref("browser.ml.chat.nimbus", "ai-chatbot-page-summarization-mvp-treatment-a-callout-badge-rollout-v4:treatment-a-callout-badge");
user_pref("browser.newtabpage.activity-stream.discoverystream.merino-provider.ohttp.enabled", true);
user_pref("browser.newtabpage.activity-stream.discoverystream.sections.interestPicker.visibleSections", "top_stories_section,worldcup,headlines,nfl,in-conversation,education-science,small-wins,by-the-numbers,explained,arts,food,in-the-zeitgeist,music,government,health,hobbies,travel,photojournalism,featured-videos");
user_pref("browser.newtabpage.activity-stream.discoverystream.sections.personalization.inferred.enabled", true);
user_pref("browser.newtabpage.activity-stream.impressionId", "{b04bb08e-3068-40df-a6f5-9ac4dffe320e}");
user_pref("browser.newtabpage.activity-stream.newtabWallpapers.user.enabled.migrated", true);
user_pref("browser.newtabpage.activity-stream.telemetry.privatePing.inferredInterests.enabled", true);
user_pref("browser.newtabpage.activity-stream.telemetry.surfaceId", "NEW_TAB_EN_US");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.newtabpage.trainhopAddon.version", "153.4.20260610.40323");
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1782148896);
user_pref("browser.search.region", "US");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20260527083644");
user_pref("browser.startup.homepage_override.mstone", "151.0.2");
user_pref("browser.startup.lastColdStartupCheck", 1782148896);
user_pref("browser.termsofuse.prefMigrationCheck", true);
user_pref("browser.theme.toolbar-theme", 0);
user_pref("browser.toolbarbuttons.introduced.sidebar-button", true);
user_pref("browser.topsites.contile.cacheValidFor", 10800);
user_pref("browser.topsites.contile.lastFetch", 1782148897);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"sidebar-button\",\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"vertical-spacer\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"ipprotection-button\",\"fxa-toolbar-menu-button\",\"reset-pbm-toolbar-button\",\"unified-extensions-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"vertical-tabs\":[],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"reset-pbm-toolbar-button\",\"developer-button\",\"screenshot-button\",\"ipprotection-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"vertical-tabs\"],\"currentVersion\":24,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 7);
user_pref("captchadetection.lastSubmission", 1782148);
user_pref("datareporting.dau.cachedUsageProfileGroupID", "0f6fe6f0-c053-45c2-8786-74cfcde2f7fb");
user_pref("datareporting.dau.cachedUsageProfileID", "108df891-18db-46b4-8153-edd501ee033c");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1782148896545");
user_pref("distribution.fedora.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "151.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "US");
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "53befd374bee49f5b62e860e3b532e2c");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.colorway-builtin-themes-cleanup", 1);
user_pref("extensions.databaseSchema", 37);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20260527083644");
user_pref("extensions.lastAppVersion", "151.0.2");
user_pref("extensions.lastPlatformVersion", "151.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.signatureCheckpoint", 1);
user_pref("extensions.webextensions.uuids", "{\"data-leak-blocker@mozilla.com\":\"566e9a7f-b10b-4bca-ba29-8e1e1fedca54\",\"formautofill@mozilla.org\":\"3517a3a9-437a-4867-9a97-64e3eaa2be52\",\"ipp-activator@mozilla.com\":\"1fb75196-47d1-4f1c-9a6c-c9b3145d2b36\",\"pictureinpicture@mozilla.org\":\"755c0c37-b483-4dc9-8760-1043f82bcb91\",\"addons-search-detection@mozilla.com\":\"b40d2b01-5c30-40b7-97b0-115b0921ac12\",\"webcompat@mozilla.org\":\"9a310967-e580-48bf-b3e8-4eafebbc122d\",\"newtab@mozilla.org\":\"5cab687b-374c-4f8a-8d3a-e7a3c4f770b7\",\"default-theme@mozilla.org\":\"57e6ba2d-22b8-43ab-8902-4456daf6ba45\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.CHIPS.lastMigrateDatabase", 2);
user_pref("network.cookie.validation.lastEpoch", 1);
user_pref("nimbus.firstUpdateComplete", true);
user_pref("nimbus.migrations.after-remote-settings-update", 0);
user_pref("nimbus.migrations.after-store-initialized", 3);
user_pref("nimbus.migrations.init-started", 1);
user_pref("nimbus.profileId", "43b66860-c386-4948-9b9f-4b527112fea4");
user_pref("nimbus.profilesdatastoreservice.read.enabled", true);
user_pref("nimbus.profilesdatastoreservice.sync.enabled", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("privacy.clearOnShutdown_v2.formdata", true);
user_pref("privacy.sanitize.clearOnShutdown.hasMigratedToNewPrefs3", true);
user_pref("privacy.sanitize.pending", "[]");
user_pref("privacy.trackingprotection.allow_list.hasMigratedCategoryPrefs", true);
user_pref("services.settings.server", "https://firefox.settings.services.mozilla.com/v1");
user_pref("services.sync.engine.addresses.available", true);
user_pref("sidebar.backupState", "{\"command\":\"\",\"panelOpen\":false,\"bookmarksExpandedFolders\":[],\"launcherExpanded\":false,\"launcherVisible\":false}");
user_pref("sidebar.main.tools", "aichat,syncedtabs,history,bookmarks");
user_pref("sidebar.nimbus", "upgraded-sidebar-rollout-without-messaging:rollout-treatment");
user_pref("sidebar.notification.badge.aichat", true);
user_pref("sidebar.revamp", true);
user_pref("sidebar.visibility", "hide-sidebar");
user_pref("toolkit.profiles.storeID", "97ee1064");
user_pref("toolkit.startup.last_success", 1782148894);
user_pref("toolkit.telemetry.cachedClientID", "80b3b69d-88e8-48a0-b58c-e32038421226");
user_pref("toolkit.telemetry.cachedProfileGroupID", "2a3689c2-ca91-4d96-a318-0a79f407f799");
user_pref("toolkit.telemetry.previousBuildID", "20260527083644");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
