# vim:ft=kitty

## name: Base2Tone Garden Dark
## author: Bram de Haan (https://github.com/atelierbram)
## license: MIT
## upstream: https://github.com/atelierbram/Base2Tone-kitty/blob/main/themes/base2tone-garden-dark.conf
## blurb: duotone theme | lime garden green - muted orange


#: The basic colors

foreground #969c96
background #1e1f1e
selection_foreground #969c96
selection_background #2b2c2a


#: Cursor colors

cursor #5F635F
cursor_text_color #1e1f1e


#: URL underline color when hovering with mouse

url_color #b7e3b5


#: kitty window border colors and terminal bell colors

active_border_color #505350
inactive_border_color #1e1f1e
bell_border_color #1c8217
visual_bell_color none


#: OS Window titlebar colors

wayland_titlebar_color #2b2c2a
macos_titlebar_color #2b2c2a


#: Tab bar colors

active_tab_foreground #fbfaf8
active_tab_background #1e1f1e
inactive_tab_foreground #b7aa9f
inactive_tab_background #2b2c2a
tab_bar_background #2b2c2a
tab_bar_margin_color none


#: Colors for marks (marked text in the terminal)

mark1_foreground #1e1f1e
mark1_background #25931f
mark2_foreground #1e1f1e
mark2_background #978678
mark3_foreground #1e1f1e
mark3_background #c96a1d


#: The basic 16 colors

#: black
color0 #1e1f1e
color8 #4a4d49

#: red
color1 #5a8065
color9 #9a7858

#: green
color2 #9a7a4a
color10 #2b2c2a

#: yellow
color3 #a89a8c
color11 #505350

#: blue
color4 #506358
color12 #4a504a

#: magenta
color5 #9a7a4a
color13 #506358

#: cyan
color6 #506358
color14 #885a28

#: white
color7 #8a908a
color15 #8aaa8a
