background = 0xff3a3f44
base = 0xff3a3f44
text = 0xffB5BBC7
alternate_base = 0xff3a3f44
bright_text = 0xffB5BBC7
accent = 0xff66707D
accent_secondary = 0xff66707D

font_family = JetBrainsMono Nerd Font Mono
font_family_monospace = JetBrainsMono Nerd Font Mono
font_size = 15

rounding_large = 0
rounding_small = 0
